### ISSUE TITLE
Setting Pre-Equalization and Post-Equalization

### ISSUE THREAD

**Issue by Astroa7m** [soygabimoreno/AudioClean#2]
dynamicsProcessing.setPostEqBandAllChannelsTo(position, band)
            dynamicsProcessing.setPreEqBandAllChannelsTo(position, band)

Setting pre and post-equalization can affect the sound quality of the audio. However, it’s possible that the settings you used for both pre and post-equalization are not optimal for the audio. You may want to try adjusting the settings for each one separately and see if that improves the sound quality. I found out that pre-Equalization alone makes it sound like a legacy Equalizer from the AudioEffects package.

**Comment by soygabimoreno** [comment]
> ```
>         dynamicsProcessing.setPostEqBandAllChannelsTo(position, band)
>         dynamicsProcessing.setPreEqBandAllChannelsTo(position, band)
> ```
> 
> Setting pre and post-equalization can affect the sound quality of the audio. However, it’s possible that the settings you used for both pre and post-equalization are not optimal for the audio. You may want to try adjusting the settings for each one separately and see if that improves the sound quality. I found out that pre-Equalization alone makes it sound like a legacy Equalizer from the AudioEffects package.

Yeah... it's not optimized at all. It's rather a demo app. Thanks for the feedback! ☺️
